//uart komutlari
#define COMMANDSLITNOLARINIGONDER				8
#define COMMANDSLITAYARLA						7
#define COMMANDCLEARSCREEN 						6
#define COMMANDVERTICALCALIBRATIONSETPROJECTOR	5
#define COMMANDVERTICALCALIBRATION				4
#define COMMANDSLITDISTANCE						3
#define COMMANDSLITSIZE							2
#define COMMANDPOSITION							1
